DROP TABLE IF EXISTS micro_data; 

CREATE TABLE IF NOT EXISTS micro_data (
    source_study TEXT NOT NULL,
    accession TEXT NOT NULL,
    alias INT NOT NULL,
    center_name TEXT NOT NULL,
    broker_name TEXT NOT NULL,
    title TEXT NOT NULL,
    taxon_id INT NOT NULL,
    scientific_name TEXT NOT NULL,
    common_name TEXT,
    description TEXT,
    bio_material TEXT,
    culture_collection TEXT,
    specimen_voucher TEXT,
    collected_by TEXT,
    collection_date DATE NOT NULL,
    country TEXT,
    host TEXT NOT NULL,
    identified_by TEXT,
    isolation_source TEXT NOT NULL,
    lat_lon TEXT,
    lab_host TEXT,
    environmental_sample TEXT,
    mating_type TEXT,
    sex TEXT NOT NULL,
    cell_type TEXT,
    dev_stage TEXT,
    tissue_type TEXT,
    cultivar TEXT,
    ecotype TEXT,
    isolate TEXT,
    strain TEXT,
    sub_species TEXT,
    cell_line TEXT,
    serotype TEXT,
    serovar TEXT,
    custom_attributes TEXT NOT NULL
);